### ISSUE TITLE
erro de nao devolver o prompt ocorre apenas a partir da segunda vez

### ISSUE THREAD

**Issue by Vinni-Cedraz** [astahjmo/minishell#79]
![Screenshot from 2023-07-19 09-10-02](https://github.com/astahjmo/minishell/assets/92558763/dcefa834-e7fb-4c91-9381-37648affc3e1)

**Comment by Vinni-Cedraz** [comment]
no exemplo da foto, devolveu o prompt na primeira vez e na segunda nao. Eh aleatorio,  poderia ter sido o ooposto

**Comment by astahjmo** [comment]
#78
