### ISSUE TITLE
Redirects and commands do not stop when an error occurs

### ISSUE THREAD

**Issue by astahjmo** [astahjmo/minishell#80]

**Comment by Vinni-Cedraz** [comment]
como assim nao param quando um erro ocorre?
tipo 
```
(comando valido) > (comand invalido) > (comando valido)

ou

(comando valido) | (comand invalido) | (comando valido)
```
dai ele executa o ultimo comando em vez de parar apos o segundo dar errado?

**Comment by Vinni-Cedraz** [comment]
Eh isso aqui?

![Screenshot from 2023-07-21 09-52-41](https://github.com/astahjmo/minishell/assets/92558763/69653f02-05c4-4d3a-ba66-5a2d23bddd95)

**Comment by Vinni-Cedraz** [comment]
fixed by Fix redirects errors merge
